version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - challenge-db:/var/lib/postgresql/data

  challenge:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      SERVER_PORT: 3000
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  challenge-db:
